name: "Start Deploy"
description: "Triggers the deployment by calling the API"
inputs:
  GH_TOKEN:
    description: "GitHub token to authenticate"
    required: true
  GH_USER:
    description: "GitHub user owner of the repository"
    default: "thiagosol"
  DEPLOY_URL:
    description: "Deploy service URL"
    default: "http://deploy.thiagosol.com/deploy"
  LOG_URL:
    description: "Deploy logs URL"
    default: "https://deploy.thiagosol.com/logs"
runs:
  using: "composite"
  steps:
    - name: Clone secrets repository
      run: |
        git clone https://oauth2:${{ inputs.GH_TOKEN }}@github.com/thiagosol/secrets.git
        mv secrets/secrets.json secrets.json
      shell: bash

    - name: Read secrets from JSON file
      id: secrets
      run: |
        # Inicializa um array vazio no formato correto
        SECRETS_ARRAY="[]"

        for key in $(jq -r 'keys_unsorted[]' secrets.json); do
          value=$(jq -r --arg key "$key" '.[$key]' secrets.json)
          echo "::add-mask::$value"

          # Adiciona ao ambiente do GitHub Actions
          echo "$key=$value" >> $GITHUB_ENV

          # Adiciona no array no formato ["VAR=VAL", "VAR2=VAL2"]
          SECRETS_ARRAY=$(echo "$SECRETS_ARRAY" | jq --arg entry "$key=$value" '. + [$entry]')
        done

        # Salva o array no ambiente
        echo "SECRETS_ENV_VARS=$SECRETS_ARRAY" >> $GITHUB_ENV
      shell: bash

    - name: Debug environment variables before calling API
      run: |
        echo "🔍 Debugging environment variables:"
        echo "DEPLOY_USER: $DEPLOY_USER"
        echo "DEPLOY_PASS: $DEPLOY_PASS"
        echo "GH_TOKEN: ${GH_TOKEN:0:5}*** (masked)"
        echo "🔍 SECRETS_ENV_VARS being sent: $SECRETS_ENV_VARS"
      shell: bash

    - name: Call Deploy API
      run: |
        AUTH="${DEPLOY_USER}:${DEPLOY_PASS}"
        echo "::add-mask::$AUTH"

        echo "🔍 JSON_ENV_VARS being sent: $SECRETS_ENV_VARS"

        RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "${{ inputs.DEPLOY_URL }}" \
          -u "$AUTH" \
          -H "Content-Type: application/json" \
          -d '{
            "service": "${{ github.event.repository.name }}",
            "branch": "${{ inputs.GH_USER }}",
            "env_vars": '"$SECRETS_ENV_VARS"'
          }')

        echo "🔍 API Response Code: $RESPONSE"

        if [ "$RESPONSE" -ne 200 ]; then
          echo "❌ Error calling the deploy API! HTTP code: $RESPONSE"
          echo "ℹ Deploy API response:"
          cat response.json
          exit 1
        fi

        echo "🚀 Deploy started for ${{ github.event.repository.name }}!"
      shell: bash
