name: Finish Deploy

on:
  repository_dispatch:
    types: [deploy_finished]

jobs:
  finish-deploy:
    runs-on: ubuntu-latest
    if: github.event.client_payload.run_id != ''
    steps:
      - name: Update Original Workflow Status
        run: |
          STATUS="${{ github.event.client_payload.status }}"
          CONCLUSION=$([ "$STATUS" == "success" ] && echo "success" || echo "failure")
          
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/check-runs/${{ github.event.client_payload.run_id }}" \
            -d "{\"status\":\"completed\",\"conclusion\":\"$CONCLUSION\"}"

      - name: Finish Deploy
        uses: thiagosol/scripts/.github/actions/finish-deploy@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
