name: Start Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start Deploy
        uses: thiagosol/scripts/.github/actions/start-deploy@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  finish-deploy:
    needs: start-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Webhook (Finish Deploy)
        run: echo "Aguardando webhook para finalizar deploy..."
